# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###regist-request
POST http://localhost:8080/api/users
Content-Type: application/json

{"userId": "durinId", "password" : "password", "name":"lee"}

###


###login-request
POST http://localhost:8080/api/users/authentication
Content-Type: application/json

{"userId": "durin93", "password" : "1234"}

###show-request
GET http://localhost:8080/api/users/1
Content-Type: application/json


###

